version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/"
      - "/examples/**/*"
    schedule:
      interval: weekly
      timezone: America/Chicago
    cooldown:
      default-days: 7
    labels:
      - dependabot 🤖
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      timezone: America/Chicago
    cooldown:
      default-days: 7
    labels:
      - dependabot 🤖
    groups:
      gha:
        patterns:
          - "*"
